a
Signed-off-by: smallyunet <dev.wangyu@gmail.com>

diff --git a/.github/workflows/publish-release-docker.yml b/.github/workflows/publish-release-docker.yml
--- a/.github/workflows/publish-release-docker.yml
+++ b/.github/workflows/publish-release-docker.yml
@@ -20,45 +20,45 @@ jobs:
           echo "GITHUB_TAG_VERSION=$TAG_VERSION" >> ${GITHUB_ENV}
           echo "Tag version is: $TAG_VERSION"
 
-  check-changelog:
-    needs:
-      - check-branch
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        if: inputs.skip_checks != true
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
+  # check-changelog:
+  #   needs:
+  #     - check-branch
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout code
+  #       if: inputs.skip_checks != true
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
 
-      - name: Install jq
-        run: sudo apt-get update && sudo apt-get install -y jq
+  #     - name: Install jq
+  #       run: sudo apt-get update && sudo apt-get install -y jq
 
-      - name: Get latest commit SHA of Main & Current Tag
-        if: inputs.skip_checks != true
-        id: get-main-sha
-        run: |
-          SHA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-          https://api.github.com/repos/${{ github.repository }}/git/ref/heads/main | jq -r '.object.sha')
-          echo "MAIN_SHA=${SHA}" >> ${GITHUB_ENV}
-          echo "CURRENT_BRANCH_SHA=${{ github.sha }}" >> ${GITHUB_ENV}
+  #     - name: Get latest commit SHA of Main & Current Tag
+  #       if: inputs.skip_checks != true
+  #       id: get-main-sha
+  #       run: |
+  #         SHA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+  #         https://api.github.com/repos/${{ github.repository }}/git/ref/heads/main | jq -r '.object.sha')
+  #         echo "MAIN_SHA=${SHA}" >> ${GITHUB_ENV}
+  #         echo "CURRENT_BRANCH_SHA=${{ github.sha }}" >> ${GITHUB_ENV}
 
-      - name: Check for CHANGELOG.md changes
-        if: inputs.skip_checks != true
-        run: |
-          echo "Check the changelog has actually been updated from whats in main"
-          CHANGELOG_DIFF=$(git diff ${MAIN_SHA}..${CURRENT_BRANCH_SHA} -- CHANGELOG.md)
-          if [ -z "$CHANGELOG_DIFF" ]; then
-            echo "ERROR: No changes detected in CHANGELOG.md. Please update the changelog."
-            exit 1
-          else
-            echo "CHANGELOG.md has been updated."
-          fi
+  #     - name: Check for CHANGELOG.md changes
+  #       if: inputs.skip_checks != true
+  #       run: |
+  #         echo "Check the changelog has actually been updated from whats in main"
+  #         CHANGELOG_DIFF=$(git diff ${MAIN_SHA}..${CURRENT_BRANCH_SHA} -- CHANGELOG.md)
+  #         if [ -z "$CHANGELOG_DIFF" ]; then
+  #           echo "ERROR: No changes detected in CHANGELOG.md. Please update the changelog."
+  #           exit 1
+  #         else
+  #           echo "CHANGELOG.md has been updated."
+  #         fi
 
-      - name: Mark Job Complete Skipped
-        if: inputs.skip_checks == true
-        shell: bash
-        run: echo "continue"
+  #     - name: Mark Job Complete Skipped
+  #       if: inputs.skip_checks == true
+  #       shell: bash
+  #       run: echo "continue"
 
   publish-release:
     permissions:
@@ -67,7 +67,7 @@ jobs:
       attestations: write
     if: inputs.skip_release != true
     needs:
-      - check-changelog
+      # - check-changelog
       - check-branch
     runs-on: ubuntu-latest
     timeout-minutes: 60
